### ISSUE TITLE
Provide example buf.lint.yaml

### ISSUE THREAD

**Issue by f0o** [protoc-extensions/protoc-gen-gapi-lint#1]
buf.lint.yaml doesnt seem to exist in buf - so what's expected there?

**Comment by iamralch** [comment]
@f0o 

```
---
version: v1

managed:
  enabled: true
  go_package_prefix:
    default: github.com/<your-org>/<your-repo>/proto
    except:
      - buf.build/googleapis/googleapis
      - buf.build/bufbuild/protovalidate
      - buf.build/protoc-extensions/protoc-gen-go-defaults

plugins:
  - name: gapi-lint
    out: internal/proto
    opt:
      - paths=source_relative
      - config=buf.lint.yaml
``` 

```
# buf.lint.yaml
---
- disabled_rules:
    - core::0133::request-unknown-fields
    - core::0134::request-unknown-fields
    - core::0135::request-unknown-fields
    - core::0235::request-unknown-fields
    - core::0133::request-required-fields
    - core::0134::request-required-fields
    - core::0131::response-message-name
    - core::0133::response-message-name
    - core::0135::response-message-name
    - core::0134::response-message-name
    - core::0121::resource-must-support-get
```
